In [36]:
import pandas as pd

In [37]:
df=pd.read_csv("/content/student_performance.csv")

In [38]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [39]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [40]:
df.shape

(30, 13)

In [41]:
df.dtypes

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [42]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [43]:
df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [44]:
df['name']

0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [45]:
df.sort_values('city')

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             30 non-null     int64
 1   name                   30 non-null     object
 2   age                    30 non-null     int64
 3   gender                 30 non-null     object
 4   department             30 non-null     object
 5   semester               30 non-null     int64
 6   math_score             30 non-null     int64
 7   science_score          30 non-null     int64
 8   english_score          30 non-null     int64
 9   programming_score      30 non-null     int64
 10  attendance_percentage  30 non-null     int64
 11  city                   30 non-null     object
 12  admission_year         30 non-null     int64
dtypes: int64(9), object(4)
memory usage: 3.2+ KB

In [47]:
df.shape[0]
df.shape[1]

13

In [48]:
df.columns.tolist()

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [49]:
df.gender

0       Male
1     Female
2       Male
3     Female
4       Male
5     Female
6       Male
7     Female
8       Male
9     Female
10      Male
11    Female
12      Male
13    Female
14      Male
15    Female
16      Male
17    Female
18      Male
19    Female
20      Male
21    Female
22      Male
23    Female
24      Male
25    Female
26      Male
27    Female
28      Male
29    Female
Name: gender, dtype: object

In [50]:
df.fillna(0)

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [51]:
cs_students=df[df["department"]=="Computer Science"]

In [52]:
cs_students.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023

In [53]:
high_attendance=df[df["attendance_percentage"]> 90]

In [54]:
df.department.unique()
df.department.value_counts()

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [55]:
df["total_score"] = df["math_score"] + df["science_score"] + df["english_score"] + df["programming_score"]

In [56]:
top_student = df.loc[df['total_score'].idxmax()]

In [57]:
print(top_student['name'])

Ananya Das

# PRACTICE QUESTIONS:

1. How many students are from the Electronics Department?
2. What is the average attendance of female students?
3. who is the student with the lowest programming score?
4. How many students scored above 80 in math?
5. What  is the average total_score for students with attendance above 90%?

In [58]:
students_in_ec = df[df["department"]=="Electronics"];
print("Total Number of Students in Electronics:")
print(len(students_in_ec))

Total Number of Students in Electronics:
6

In [59]:
female_students = df[df['gender']=="Female"]
avg_attendance = female_students["attendance_percentage"].mean()
print(avg_attendance)

88.53333333333333

In [60]:
df_sort_prog_score = df.sort_values(by="programming_score",ascending= True)
print(df_sort_prog_score['name'].head(1))

16    Manoj Pandey
Name: name, dtype: object

In [61]:
math_above_80 = df[df["math_score"] > 80].shape[0]
print("Students Scored Above 80 in Math:", math_above_80)

Students Scored Above 80 in Math: 11

In [62]:
avg_total = df[df["attendance_percentage"] > 90]["total_score"].mean()
print(" Average Total Score (Attendance > 90%):", avg_total)

 Average Total Score (Attendance > 90%): 335.8

MINI PROJECT : Student Data explorer
Objective:
Create a student performance explorer using pyhton and pandas to analayse student data and generate a detailed report
Dataset columns:
name
gender
dept
math_score
programming_score
attendance_score
total_score
Tasks to perform:
diplay proj title
print a formated title with separator lines
display
total no of columns
total no of students
no of unique depts
display the count of students in each dept
find and display highest math score
lowest math score
avg math score
avg prog score
avg attendance percentage
cal and display avg total score grouped by gender
top performers
display top 5 scorers based on total scores
show student name
dept
total score
find students whose attendance is below 75%
display name
dept
attendance percentage
if all above 75% att print a suitable message

In [68]:
import pandas as pd


df = pd.read_csv("student_performance.csv")

df["total_score"] = df["math_score"] + df["science_score"] + df["english_score"] + df["programming_score"]

print("=" * 60)
print("      STUDENT PERFORMANCE ANALYSIS USING PANDAS")
print("=" * 60)

print("\nTOTAL NO OF COLUMNS :", len(df.columns))
print("TOTAL NO OF STUDENTS :", len(df))
print("NO OF UNIQUE DEPARTMENTS :", df['department'].nunique())

print("\n" + "=" * 60)
print("COUNT OF STUDENTS IN EACH DEPARTMENT")
print("=" * 60)

dept_count = df['department'].value_counts()

for dept, count in dept_count.items():
    print(dept, ":", count)

print("\n" + "=" * 60)
print("MATH SCORE ANALYSIS")
print("=" * 60)

print("HIGHEST MATH SCORE :", df['math_score'].max())
print("LOWEST MATH SCORE :", df['math_score'].min())
print("AVERAGE MATH SCORE :", round(df['math_score'].mean(), 2))

print("\nAVERAGE PROGRAMMING SCORE :", round(df['programming_score'].mean(), 2))

print("AVERAGE ATTENDANCE PERCENTAGE :", round(df['attendance_percentage'].mean(), 2))

print("\n" + "=" * 60)
print("AVERAGE TOTAL SCORE GROUPED BY GENDER")
print("=" * 60)

gender_avg = df.groupby('gender')['total_score'].mean()

for gender, avg in gender_avg.items():
    print(gender, ":", round(avg, 2))

print("\n" + "=" * 60)
print("TOP 5 PERFORMERS")
print("=" * 60)

top5 = df.sort_values(by='total_score', ascending=False).head(5)

print(top5[['name', 'department', 'total_score']])

print("\n" + "=" * 60)
print("STUDENTS WITH ATTENDANCE BELOW 75%")
print("=" * 60)

low_attendance = df[df['attendance_percentage'] < 75]

if len(low_attendance) > 0:
    print(low_attendance[['name', 'department', 'attendance_percentage']])
else:
    print("All students have attendance above 75%")

============================================================
      STUDENT PERFORMANCE ANALYSIS USING PANDAS
============================================================

TOTAL NO OF COLUMNS : 14
TOTAL NO OF STUDENTS : 30
NO OF UNIQUE DEPARTMENTS : 4

============================================================
COUNT OF STUDENTS IN EACH DEPARTMENT
============================================================
Computer Science : 13
Electronics : 6
Mechanical : 6
Civil : 5

============================================================
MATH SCORE ANALYSIS
============================================================
HIGHEST MATH SCORE : 95
LOWEST MATH SCORE : 56
AVERAGE MATH SCORE : 76.07

AVERAGE PROGRAMMING SCORE : 67.6
AVERAGE ATTENDANCE PERCENTAGE : 84.5

============================================================
AVERAGE TOTAL SCORE GROUPED BY GENDER
============================================================
Female : 310.67
Male : 280.67

============================================================
TOP 5 PERFORMERS
============================================================
              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356

============================================================
STUDENTS WITH ATTENDANCE BELOW 75%
============================================================
             name   department  attendance_percentage
5     Meera Joshi  Electronics                     72
8    Rahul Mishra   Mechanical                     68
16   Manoj Pandey        Civil                     65
20  Harish Pillai  Electronics                     74
22   Sanjay Dubey        Civil                     70
27  Sunita Pillai        Civil                     73